### ISSUE TITLE
Feature Idea: Error Handler frame receives previous (error producing) state as Argument

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-State-Machine#11]
One thing that people have asked for is to know which frame caused an error. Currently, the JKI State Machine will detect that an error has occurred and then will execute the Error Handler frame instead processing the remaining state queue:

**Step 1 - Error Occurs**
![image](https://user-images.githubusercontent.com/381432/49677894-fc6cce80-fa35-11e8-8892-9b53c4c807e3.png)

**Step 2 - JKI SM forces the Error Handler frame to execute**
![image](https://user-images.githubusercontent.com/381432/49677864-df380000-fa35-11e8-8805-3311cd504b0d.png)

**Possibilities - Custom Error Handling for Different States**
![image](https://user-images.githubusercontent.com/381432/49678027-caa83780-fa36-11e8-919e-b57117f9a078.png)

**Open Questions and Considerations**
- Should such specialized error handling be done inside the actual frame that generated the error, instead of putting it into the catch all Error Handler?
- Should arguments of the state call (where the error occurred) also be included, or just the state name that generated the error? (Maybe the arguments passed to the state contribute to the error)
- Should we, instead, make the Previous State available to all frames of the JKI State Machine (e.g. as an additional output to the Parse State Queue), instead only adding it to the Error Handler as an argument?

**Comment by francois-normandin** [comment]
I personally like this idea very much.
My preference would be to pass the previous state with arguments, so that one could reuse the same method to parse in the error handler case. 

![image](https://user-images.githubusercontent.com/11728548/58748932-72824900-844d-11e9-9738-7d62245a7713.png)

**Comment by Tom-McQuillan** [comment]
I've been after this for sometime. After seeing #14 I was hoping this was already a feature I had somehow missed. However this feature does not appear in the current build :(

My ideal solution:
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/104849466/75dac463-4331-4a6a-a787-113a1be212b0)


![image](https://github.com/JKISoftware/JKI-State-Machine/assets/104849466/0f0eae20-b5f6-4611-b6c3-4f7944f3ad68)

**Comment by oipatet** [comment]
Hy, this is our idea that is used in our company. Maybe it's a little inspiration.

![image](https://github.com/user-attachments/assets/d0761d7a-0d7d-4683-b25f-4eb8260e4c56)

![image](https://github.com/user-attachments/assets/259d0880-2beb-412a-b8c4-0e9176bf097d)

![image](https://github.com/user-attachments/assets/13061689-dad2-48ba-93b8-e68a63c34115)
