### ISSUE TITLE
Unable to install the JKI SM using VIPM 2014

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine#12]
In fact the message says that I can't install with any VIPM prior to 2017.  So I had to manually select old version of state machine to use in my PC.

![image](https://user-images.githubusercontent.com/6551395/51383773-41465380-1b12-11e9-82fe-1cc07aff325f.png)

**Comment by jimkring** [comment]
Yes, you'll need to [upgrade to VIPM 2017 or newer](https://vipm.jki.net/get).
