### ISSUE TITLE
'Insert "Add State(s) to Queue"' fails

### ISSUE THREAD

**Issue by jlj-ee** [JKISoftware/JKI-State-Machine#13]
Version info:
JKI State Machine v2018.0.6.44
LabVIEW 2016
Windows 10

Steps to reproduce:
1. Open a blank VI
2. Place a new JKI SM
3. Right-click on the state string wire; select 'Insert "Add State(s) to Queue"':
![image](https://user-images.githubusercontent.com/11401637/51706647-1d40b180-1fed-11e9-9a90-1df1a99dc93f.png)
4. Get the following pop-up:
![image](https://user-images.githubusercontent.com/11401637/51706615-0732f100-1fed-11e9-8e30-e9a57d8c8912.png)

This was not an issue in prior versions, but is currently reproducible 100% of the time for me.

**Comment by jimkring** [comment]
Good catch @jlj-ee. Fixed in https://github.com/JKISoftware/JKI-State-Machine/releases/tag/2018.0.7.45 -- available for [download with VIPM](https://resources.jki.net/state-machine).

**Comment by jlj-ee** [comment]
Thanks as always @jimkring!
