### ISSUE TITLE
"OK" button of JKI SM template should be bound to <Escape> key instead of <Enter> (and should be renamed "Exit")

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-State-Machine#20]
Currently, pressing the <Enter> key causes the "OK" button of the template to toggle to TRUE and calls Macro: Exit. This is not a desirable behavior and nearly every developer ends up having to fix this in their code. Instead, the button should be bound to the <Escape> key and renamed to "Exit" so that it's clear to users how it functions.

**Comment by Tom-McQuillan** [comment]
Keybinding removed in JKISM24
