### ISSUE TITLE
Add "VI Name" as "error source" for "General Error Handler.vi" function

### ISSUE THREAD

**Issue by kosist** [JKISoftware/JKI-State-Machine#23]
I have use case when multiple VIs with JKI State Machine are launched dynamically. And in case of some error, it is difficult to find out where exactly it has happened (based on default error dialog).
The easy solution could be to assign "VI Name" to "error source" of the "General Error Handler.vi" - and user will immediately see, which VI drops the error...

![Error Dialog](https://user-images.githubusercontent.com/1911151/86325116-d8886380-bc3f-11ea-810d-78245a981a76.png)

**Comment by Tom-McQuillan** [comment]
I'm looking at the `General Error Handler Core CORE.vi` source and it looks like the `error source` input is discarded if there is a valid error.
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/104849466/6176c764-aeaf-47b2-9701-c4bf53b22c94)

A solution I have used in the past is to use the error `<append>` function to append the VI Name/Title and state that caused the error to the error message. Getting the state that caused the error involved having to use a feedback node to retain state-1

**Comment by Tom-McQuillan** [comment]
Similar feature implemented in JKI SM24
