### ISSUE TITLE
Warnings are never cleared

### ISSUE THREAD

**Issue by Tom-McQuillan** [JKISoftware/JKI-State-Machine#29]
If a warning occurs (for example, if the number of VISA bytes read matches the buffer size a warning is injected), it can never leave the error shift registers.

Proposal: In the template create a new Warning Handler (along side the existing Error Handler) state. The default behavior will be to clear the warning.

**Comment by drjdpowell** [comment]
I would suggest you just drop the warning in the "Idle" case.  There is never an error there.

**Comment by Tom-McQuillan** [comment]
@drjdpowell Are you suggesting clearing the warnings before the event structure? as per the screenshot?
I like this approach as it would be backwards compatible. However, it doesn't allow the developer to handle the warning -> that being said, it's never been a feature before (and AFAIK never something anyone has asked for)
![image](https://github.com/JKISoftware/JKI-State-Machine/assets/104849466/b4680135-787c-4d2a-8a62-056628feb866)

**Comment by drjdpowell** [comment]
Yes, that's right.

I have never seen code where a warning is actually handled.

**Comment by jimkring** [comment]
How about this as a solution? Parse State Queue could route to the `Error Handler` frame if it detects a warning.

@drjdpowell, @Tom-McQuillan, @philippe-guerit, @HunterJKI  can you think of any unintended side-effects that would make such a change problematic for existing applications?

One could argue that it's good user might see warnings show up in the Error Handler frame that they previously did not know about.

![image](https://github.com/JKISoftware/JKI-State-Machine/assets/381432/25d88438-8755-41a6-88a3-711a563e3199)

**Comment by Tom-McQuillan** [comment]
I like this solution, but would have Post Action states conditional on
incoming errors not warnings

**Comment by Tom-McQuillan** [comment]
Resolved in #31
