### ISSUE TITLE
JKI State Machine 2024 Release Planning

### ISSUE THREAD

**Issue by jimkring** [JKISoftware/JKI-State-Machine#33]
This is a living issue that Jim will update

## What’s new
- [Update] LabVIEW 2020+ Compatibility
  - Upgraded sources to LabVIEW 2020 and separated compiled code
- [New] State Utilities
  - Conditional State - 
  - Periodic State - 
  - Select State(?) - [to review]
  - [Change] Warnings now Routed to Error Handler frame - 
- [New] Error Handler frame receives previous state as argument
- Template Updates
  - UI Cleanup 
    - New frame for code related to clearing control/indicator values before `Exit` (Called by `Macro: Exit`)
  - Minor Typo Fixes
- Maintenance
  - VIPC file updated

## Open Issues and Questions

  - Package Dependencies (built package) - Jim: Tom asked a question about dependencies of the built package
    - Don’t want users to depend on OpenG 6.0
    - Jim thinks we should check to ensure that any package dependencies of the JKI SM utilities are internalized during the build process
  - Package Build - Tom mentioned that the package build wasn’t working (VIPM complains about declared dependencies not installed)
  - Consider LVLIB Upgrade
    - Should we move to an LVLIB instead of LLB?

## To Do
- Palette Updates
  - [x] #34
- Unit Tests
  - [x] #35
  - [x] #44
- Code Review
  - [x] Tom will lead a code review with the team for feedback
- Docs
  - [x] #36
  - [x] Create 2024 release in docs
- [x] #45
  - There are some annoyances -- little bugs

**Comment by Tom-McQuillan** [comment]
Regarding https://github.com/JKISoftware/JKI-State-Machine/issues/45, the editor has been updated for JKISM24, features/bugs of the editor will be evaluated separately to the release of JKISM24
