### ISSUE TITLE
Closing and Opening the FrontPanelState causes "Resetting VI" error

### ISSUE THREAD

**Issue by digiajay** [JKISoftware/JKI-State-Machine#4]
I want to keep the front panel closed in JKI state machine application until a business logic decides to open it up to the user.  When I use the "UI: Front Panel State >> Close", the VI immediately goes into some mode which causes "Resetting VI" error.

**Comment by jimkring** [comment]
Hi @dijiajay. Can you reproduce this on all JKI state machines? One you can share with us?

**Comment by jimkring** [comment]
@digiajay is this reproducible or should we close this issue?

**Comment by digiajay** [comment]
@jimkring I guess it's no more reproducible.  You can close this issue.

**Comment by jimkring** [comment]
Thanks @digiajay. I'll close the issue, now/
