### ISSUE TITLE
Missing VI while compiling .vipb

### ISSUE THREAD

**Issue by jarranz89** [JKISoftware/JKI-State-Machine#47]
I found there is a missing vi while I'm trying to compile a .vipb with the JKI-State Machine as a dependency of my library. 

The VI Package Manager Returns the following message: 

VI Tree - JKI State Machine API.vi	Y:\JKI\GitHub\JKI-State-Machine-Editor\source\.source\JKI State Machine API\VI Tree - JKI State Machine API.vi	

The source VI is the following: 
JKI State Machine API__JKI_State_Machine_Helper.lvlib	C:\Program Files (x86)\National Instruments\LabVIEW 2021\resource\dialog\QuickDrop\plugins\_JKI State Machine Helper.llb\JKI State Machine API__JKI_State_Machine_Helper.lvlib	

I went to the selected path and I can confirm that the VI Tree - JKI State Machine API.vi is missing. I double checked it in another computer Installing the JKI-SM from the scratch and I get the same problem.

**Comment by Tom-McQuillan** [comment]
Thanks for reporting this issue @jarranz89, we're on it.
